FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash curl build-base python3

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npx", "tsx", "watch", "src/index.ts"]
